export { FAQ } from './ayuda/FAQ'
export { CentroDeSeguridad } from './ayuda/CentroDeSeguridad'
export { SoporteTurista } from './ayuda/SoporteTurista'
export { ComoReservar } from './ayuda/ComoReservar'
export { EstadoDeReserva } from './ayuda/EstadoDeReserva'

export { Destinos } from './descubre/Destinos'
export { Tours } from './descubre/Tours'
export { Alojamientos } from './descubre/Alojamientos'
export { Transportes } from './descubre/Transportes'
export { ComidaTipica } from './descubre/ComidaTipica'
export { MapaTuristicoPage } from './descubre/MapaTuristico'

export { SobreNosotros } from './empresa/SobreNosotros'
export { MisionVision } from './empresa/MisionVision'
export { PorQueElegirnos } from './empresa/PorQueElegirnos'
export { TestimoniosPage } from './empresa/TestimoniosPage'

export { Terminos } from './legal/Terminos'
export { Privacidad } from './legal/Privacidad'
export { CookiesPage } from './legal/CookiesPage'
export { ReembolsosPage } from './legal/ReembolsosPage'
export { CancelacionPage } from './legal/CancelacionPage'

export { TurismosPasto } from './narino/TurismoPasto'
export { ToursNarino } from './narino/ToursNarino'
export { QueHacerPasto } from './narino/QueHacerPasto'
export { LugaresImperdibles } from './narino/LugaresImperdibles'

export { AventuraPage } from './experiencias/AventuraPage'
export { NaturalezaPage } from './experiencias/NaturalezaPage'
export { CulturaPage } from './experiencias/CulturaPage'
export { GastronomiaPage } from './experiencias/GastronomiaPage'
export { SenderismoPage } from './experiencias/SenderismoPage'
export { FestivalesPage } from './experiencias/FestivalesPage'

export { GuiaDelViajero } from './recursos/GuiaDelViajero'
export { ArticulosPage } from './recursos/ArticulosPage'
export { NoticiasTurismoPage } from './recursos/NoticiasTurismoPage'
export { AgenciasPage } from './recursos/AgenciasPage'
export { ColaboradoresPage } from './recursos/ColaboradoresPage'
export { AfiliadosPage } from './recursos/AfiliadosPage'
export { GuiasTuristicosPage } from './recursos/GuiasTuristicosPage'

export { Ofertas } from './promociones/Ofertas'
export { PlanesFinDeSemanaPage } from './promociones/PlanesFinDeSemanaPage'
export { ViajesBaratosPage } from './promociones/ViajesBaratosPage'

export { FeedPersonalizado } from './FeedPersonalizado'
